### ISSUE TITLE
In version 3.2.17 the fill and border transparency settings don't work for circles

### ISSUE THREAD

**Issue by jamesdales** [jamesdales/IconMapSupport#1]
In version 3.2,17 it is no longer possible to set the fill and border transparency options

**Comment by jamesdales** [comment]
Resolved in 3.1.0

**Comment by jlpnea** [comment]
Hi James
I'm in the last sept 2023 release of pbi desktop and i am in 3.3.1 of Icon map  and i love it. thanks a lot for this great job
My iconmap visual contains both circle and wkt. I'm having a problem with the formatting options.
it is possible to create the rules for fill color and border color, but it is not possible to enter the rules for fill style, border width, fill transparency, border transparency and border dash array as you can see the attached screenshoot
Do you have a solution ? king regard
![formatting 331](https://github.com/jamesdales/IconMapSupport/assets/64679075/366ad1bd-3b0b-43b6-8907-284a3f6cc433)

![wkt and circle](https://github.com/jamesdales/IconMapSupport/assets/64679075/efeb160a-ba64-45da-9d92-4890315afdc3)
