### ISSUE TITLE
Hosting large GeoJSONs

### ISSUE THREAD

**Issue by scamara-fraym** [jamesdales/IconMapSupport#12]
I've added several map layers to GitHub in order to use them for a drilldown map with the Icon Map PowerBI plugin. Two of the three layers are larger than 25mb and won't render in Icon Map using the GitHub raw URL. It also appears that the GeoJSON format is the only way to import multiple layers in the same map. Are there other hosting options for large GeoJSONs that would work with this plugin, or plans to expand other formatting options to include multiple layers?

**Comment by amarinos238** [comment]
You can do drilldown maps using vector-tile maps instead of geoJSON. You will have to have a geo-server which will be serving data in vector-tile format. This is described very detailed in James's blog usin GeoServer as a web-server. The advantage is that you can use much larger vector maps this way, since they don't need to be loaded into memory locally

**Comment by scamara-fraym** [comment]
@amarinos238 How would I go about creating a drilldown map with vector tiles? I had already tried this method and had geoserver set up, but it looked like you could only add a single vector tile layer to a map at one time. There is also no hovertext capability for vector tiles right now, so it would meet my needs at the moment.

**Comment by jamesdales** [comment]
I've tomorrow off work to catch up on Icon Map support and fixes, so will reply more fully tomorrow, but the good news is that the version of Icon Map I'll hopefully publish tomorrow does support multiple drill down levels (and tooltips/hovertext) on vector tiles.

**Comment by jamesdales** [comment]
This capability has now been published in version 3.1.0

**Comment by coyne44** [comment]
@scamara-fraym, you can also use dropbox.com (also free) to host much larger geojson files. Just replace "www.dropbox" with "dl.dropboxusercontent" in the url for it show up in icon map.

**Comment by aliciaoberholzer** [comment]
@coyne44 do you know whether the dropbox.com method you mentioned works for Box as well? That's the file management system being used at my organization.

**Comment by coyne44** [comment]
@aliciaoberholzer , I'm not familiar with Box but it looks like it's possible but has to be configured correctly on the backend. Here is a support feed that might help. https://support.box.com/hc/en-us/community/posts/12793982770579-Requesting-support-for-CORS-error-when-accessing-shared-resource
