### ISSUE TITLE
Using cql-filters in WMS-URL-string works only with static strings

### ISSUE THREAD

**Issue by amarinos238** [jamesdales/IconMapSupport#13]
Hi James,
I'm using version 3.2.17 for this. The WMS services are provided by a public WMS server from the weather service, based on geoserver. I also could verify the same behaviour using my own geoserver version 3.23.2.
I use a measure to define the URL string to be used in the WMS-URL field. This is the string:
https://brz-maps.dwd.de/geoserver/ows?SERVICE=WMS&cql_Filter=NAME IN ('Rostock','Berlin','Hamburg')
When I construct exactly the same string using a measure which concatenatexs some city-names, unfortunately only the first city is shown, but not any others.
The layername is dwd:BRD_Orte
I've been trying any variant I coulod think of for 2 days now, no success. 
Could you please help? This would be a great feature, which would enable IconMap to do filtering and intersects and the such, without having to code anything in IconMap!
I enclose here a demo-pbix for testing.
Best greets,
Andreas
[test_ecql_filter.zip](https://github.com/jamesdales/IconMapSupport/files/12327295/test_ecql_filter.zip)

**Comment by jamesdales** [comment]
This looks like a bug. I can see the URL being sent to geoserver only includes one item. Debugging it now...

**Comment by jamesdales** [comment]
Ok.... I've got to the bottom of this now.

So what's happening is because your slicer values used to create the URL for the WMS layer are in the same table as the ID field in the category field of Icon Map, it's actually generating three separate URLs, one for each ID:

https://brz-maps.dwd.de/geoserver/ows?SERVICE=WMS&&cql_Filter=NAME IN ('Rostock')
https://brz-maps.dwd.de/geoserver/ows?SERVICE=WMS&&cql_Filter=NAME IN ('Berlin')

etc.

If you disconnect the two things, so that the WMS value isn't being filtered by the map category, then it works.

**Comment by amarinos238** [comment]
Good morning, James,
Thanks you once more for providing this solution. I implemented this in my little demo pbix and it worked nicely.
Unfortunately it wasn’t so easy with my true report. That one typically uses the unique IDs of a large table  (Analytical Base Table) as the map category, and some joined other tables for the details I want to attach to the WMS-URL. I worked together with Nikola Ilic on this and we were only successful when we duplicated the large table, thus decoupling it. This of course created a lot of unnecessary data in memory, but it works.
Would there be another way within the IconMap code, to decouple WMS-string and category field?
Just a suggestion as an enhancement. I am very grateful for the present solution, which opens so many new possibilities in combination with URL-in-line filtering and intersecting.
Have a great day,
Andreas

Andreas Marinos
Consultant Data Analytics

DAA1.4

Telefon:  +49 (89) 3891-4538
Telefax:  +49 (89) 3891-74538
***@***.******@***.***>
www.munichre.com<http://www.munichre.com/>
________________________________
***@***.***
