### ISSUE TITLE
issue on dax formatting on fill style, border width, fill transparency, border transparency and border dash array

### ISSUE THREAD

**Issue by jlpnea** [jamesdales/IconMapSupport#19]
Hi James
I'm in the last sept 2023 release of pbi desktop and i am in 3.3.1 of Icon map  and i love it. thanks a lot for this great job
My iconmap visual contains both circle and wkt. I'm having a problem with the formatting options.
it is possible to create the rules for fill color and border color, but it is not possible to enter the rules for fill style, border width, fill transparency, border transparency and border dash array as you can see the attached screenshoot
Do you have a solution ? king regards. Jean-Louis
![formatting 331](https://github.com/jamesdales/IconMapSupport/assets/64679075/366ad1bd-3b0b-43b6-8907-284a3f6cc433)

![wkt and circle](https://github.com/jamesdales/IconMapSupport/assets/64679075/efeb160a-ba64-45da-9d92-4890315afdc3)

**Comment by jamesdales** [comment]
It looks like this is a Power BI limitation I'm afraid. I'll investigate more to see if there's anything I can do.

In the meantime, you can achieve the same result, but you'll need to create a DAX measure to output the result you require.

**Comment by jlpnea** [comment]
Hi James, thank you for your reply
I have done the DAX method, its ok
Thanks and regards. Jean-Louis
