### ISSUE TITLE
Enable numeric labels

### ISSUE THREAD

**Issue by rafael-costa123** [jamesdales/IconMapSupport#25]
Right now on the visual area of IconMap you can add labels that show on the map. I was trying to get numbers on the map, my idea is to classify each city based on population, but i cant manage to do it because the label can only be a text, and the rank can only be a number, a measure. Is there a way to make the label accept a numeric input?
Thank You

**Comment by J-Spain** [comment]
I've run into this before with native visuals as well. The only way I could figure out to get it work was to convert the numeric value to text.

Then you should be able to select that measure as the label.

CONVERT(Number, STRING)

-Jim
