### ISSUE TITLE
Circle size based on current zoom level

### ISSUE THREAD

**Issue by jlpnea** [jamesdales/IconMapSupport#28]
Hi James
Is it possible to have a Circle size based on current zoom level with a dax mesure ?
thanks and regards. Jean-Louis

**Comment by jamesdales** [comment]
Hi. 

I'm afraid it's not currently possible to change the circle size based on zoom. The circle size can either be:

1) (default) Static size when zoomed: In this mode the circle appears the same size on the screen regardless of the zoom level. It's diameter in km will be different, but the size on the screen will appear the same. The size of the circle depends on the value in the size field, and is scaled between the min and max values.
2) Diameter in meters: In this mode the circle takes the value in the size field and creates a circle with a diameter in meters based on that value. The diameter of the circle in km will be the same regardless of the zoom level, but will appear bigger and smaller on the screen as the map is zoomed.

Both can be set via a DAX measure, as can the above behaviour for each row.

Thanks

James
