### ISSUE TITLE
GEOJSON Label splits on both part of polygon

### ISSUE THREAD

**Issue by kadirkkkk** [jamesdales/IconMapSupport#3]
I'm working on Turkey map, in GEOJSON file İSTANBUL city has two parts as asian and european side. Althought İstanbul has just one value label (ex: sales amount), label shows on both sides and this seems like repetition on the end user side. 
(tested on vers. 3.2.17)

![image](https://github.com/jamesdales/IconMapSupport/assets/10617803/858d341c-485f-4f92-af10-d2917cb72f9c)
![image](https://github.com/jamesdales/IconMapSupport/assets/10617803/84b17943-413f-44a1-858e-ecb16b61f33d)

**Comment by jamesdales** [comment]
This shouldn't be the case - it should only be creating one label per feature - assuming that you have a multipolygon in your geojson file containing the two polygons for istanbul. If it's two separate features, then it will create two labels.

Are you able to share the geojson file?

**Comment by kadirkkkk** [comment]
Thanks for responsePolygon file is attached
    8 Haziran 2023 Perşembe 09:50:19 GMT+3 tarihinde, James Dales ***@***.***>şunu yazdı:  
 
 


This shouldn't be the case - it should only be creating one label per feature - assuming that you have a multipolygon in your geojson file containing the two polygons for istanbul. If it's two separate features, then it will create two labels.

Are you able to share the geojson file?

**Comment by jamesdales** [comment]
Thanks for sharing the file. Yes it appears Istanbul is repeated within the file:

![image](https://github.com/jamesdales/IconMapSupport/assets/37669155/6db30069-2b46-400c-876e-6825db55292b)

Merging these as a single multipolygon should work. Try the file within this zip:

[merged.zip](https://github.com/jamesdales/IconMapSupport/files/11687493/merged.zip)
