### ISSUE TITLE
Set tooltip layers priority

### ISSUE THREAD

**Issue by Jaggana69** [jamesdales/IconMapSupport#30]
Hello,

I can't post the pbix file due to sensitive information.
I'm displaying 2 types of "object" on the map, using measure to play on color and transparency (based on the type).
It's working pretty well, thanks by the way :)

My problem is, on mouse over, only the tooltip of the transparent larger circle is displayed and not the red ones: 
![image](https://github.com/jamesdales/IconMapSupport/assets/130548548/3d784ca5-f02c-4f6c-bbca-741b7fe6cf16)

![image](https://github.com/jamesdales/IconMapSupport/assets/130548548/42ad1e9f-9faf-4868-afd4-3c5e80b6b1e6)

![image](https://github.com/jamesdales/IconMapSupport/assets/130548548/f6416f2a-3e7b-4d9d-9c27-9bbd230910ac)

![image](https://github.com/jamesdales/IconMapSupport/assets/130548548/2d581864-d1d7-407f-93a5-16133536c741)

How can I make visible the tooltip of the red circle ?

**Comment by jamesdales** [comment]
Hi.

It looks like the larger circle is being drawn over the smaller ones, which despite being transparent, still blocks out the events of the smaller ones. You could try setting the visual's sort order to change the order that the objects in each layer are drawn: 

![image](https://github.com/jamesdales/IconMapSupport/assets/37669155/e5aad82d-953f-4ee7-bebe-58150071a64e)

As long as your larger circles are drawn first you should be ok.

You can then control which objects you want to show a tooltip or not, using conditional formatting on the "Show Tooltips" property of "Objects" to return Yes or No.

![image](https://github.com/jamesdales/IconMapSupport/assets/37669155/54e5dbaa-e03a-445b-9ac9-5bf7eeffdc3b)

Hope this helps

Thanks

James

**Comment by Jaggana69** [comment]
Thanks for your detailed answer @jamesdales :)
