### ISSUE TITLE
Web map tile services (WMTS) support

### ISSUE THREAD

**Issue by maphew** [jamesdales/IconMapSupport#32]
Is OGC Web Map Tile Service Implementation Standard (WMTS) supported?

 https://opengeospatial.github.io/e-learning/wmts/text/main.html

I tried adapting the WMS Layer widget controls but either my syntax is wrong or it can't be done using this widget.

This the service I'm trying to use: https://mapservices.gov.yk.ca/arcgis/rest/services/BaseMap_Cache_WebMercator/MapServer

**Comment by jamesdales** [comment]
Hi

Yes WMTS is supported either for the base map, or overlays: 

![image](https://github.com/jamesdales/IconMapSupport/assets/37669155/0cc06fa0-8fb3-4dd1-b28a-9b021ac30dc8)

The URL I used is as follows:
https://mapservices.gov.yk.ca/arcgis/rest/services/BaseMap_Cache_WebMercator/MapServer/tile/{z}/{y}/{x}?blankTile=false

Could I ask which URL you were trying, as I'm working on making this more intuitive for a future version of Icon Map?

Thanks

James

**Comment by maphew** [comment]
Ahh! that works, thank you. I didn't know about the _tile/z/x/y_ parameters.

I didn't keep a log of the things I tried, but they resembled these (3 different services, only 1 being WMT):

```
https://mapservices.gov.yk.ca/arcgis/rest/services/BaseMap_Cache_WebMercator/MapServer/WMTS/1.0.0/WMTSCapabilities.xml
https://mapservices.gov.yk.ca/arcgis/rest/services/BaseMap_Cache_WebMercator/MapServer/WMTS/1.0.0/

https://mapservices.gov.yk.ca/arcgis/services/Yukon_Basemap_Cache/MapServer/WMSServer?request=GetCapabilities&service=WMS
https://mapservices.gov.yk.ca/arcgis/services/Yukon_Basemap_Cache/MapServer/WMSServer?service=WMS
https://mapservices.gov.yk.ca/arcgis/rest/services/Yukon_Basemap_Cache/MapServer

http://wms.ess-ws.nrcan.gc.ca/wms/toporama_en?VERSION=1.1.1&service=wms
```
