### ISSUE TITLE
Lines - Dynamic width, color and label

### ISSUE THREAD

**Issue by jvanelteren** [jamesdales/IconMapSupport#36]
First of all congrats with a great visual! I'm working on a use case for energy transmission. With the energy transition in full swing, all kind of projections are being made in current and future loads on the grid.

Here the power lines itself are most interesting, not the start point or the destination.

Basically it's three things that I need to control:
- the width of the line (depends on the capacity of the line, which is a number)
- the load on the line (depends on the current flowing through it, from green to red = bad, also a number)
- the direction of the current, with an arrow pointing towards the start or endpoint of the line.

IconMap looks great, but I've not been able to make it work with the lines functionality. The label gives some freedom, but the line is only showing if you also have a circle (which I'm not interested in). Is there something I'm missing, are these potential features?

**Comment by jamesdales** [comment]
It should be possible to draw lines without circles. Are you able to share a mockup of how you're configuring in the map?

I've built a report that sounds similar to the one you're constructing:

![image](https://github.com/jamesdales/IconMapSupport/assets/37669155/ea055a8e-622a-4b1e-b3b7-a236ffbdb4f4)
