### ISSUE TITLE
Different colors for GeoJSON polygons, when drill-down through GeoJSON to circles

### ISSUE THREAD

**Issue by KazakovNsk** [jamesdales/IconMapSupport#37]
Hi. I want to assign different colors for GeoJSON polygons when use drill-down through GeoJSON to circles. Please help me

**Comment by jamesdales** [comment]
This is possible if you use DAX to return your specific colors for formatting. Then you can use the ISINSCOPE function to detect the drilldown level, and return the appropriate set of colors.
