### ISSUE TITLE
Image at destination and WKT

### ISSUE THREAD

**Issue by jbr64** [jamesdales/IconMapSupport#4]
Hi
When I use linestrings on my map thanks to WKT, I would like to put an arrow head at destination. 
The arrow head I use works fine with standard lines but does not appear when using WKT linestring.
Is there something else to do?
Thanks

**Comment by jamesdales** [comment]
Hi @jbr64. This capability isn't currently there for linestrings. However, the good news is I've already added it to the next version of Icon Map which should be released on the downloads page in the next few day.

Thanks,

James

**Comment by jbr64** [comment]
Great, makes my day... looking forward to it!
Many thanks

**Comment by jamesdales** [comment]
Added in 3.1.0
