### ISSUE TITLE
GeoJSON uploaded to Github via Large File Storage won't show up in Icon Map

### ISSUE THREAD

**Issue by aliciaoberholzer** [jamesdales/IconMapSupport#41]
We have a couple of GeoJSONs over 25MiB and used the Github Large File Storage tool to upload them to our Github Repo, but the ones over 25MiB won't show up in Icon Map. [Here](https://github.com/scamara-fraym/kenya_adms) is the repository containing the GeoJSONs. Is anyone aware of a solution for this? Our organization currently doesn't have GeoServer set up and we don't have a subscription to other storage platforms that are compatible with Icon Map. We have mapbox but mapbox vector tiles don't seem to be supported by Icon Map yet. 

I appreciate any help! Thank you!

**Comment by jamesdales** [comment]
Hi. Just to check that you're using the RAW url?

For example: https://raw.githubusercontent.com/scamara-fraym/kenya_adms/main/adm2_kenya.geojson should display as follows in Icon Map:

![image](https://github.com/jamesdales/IconMapSupport/assets/37669155/4736c514-1ff4-4283-8aef-af464311750f)

**Comment by aliciaoberholzer** [comment]
Hi @jamesdales! For some reason, it only shows me the option to copy the raw URL for the ADM1 GeoJSON - how did you happen to retrieve it? Thank you for all your help - I really appreciate it as I am learning!
![Screenshot 2024-01-10 at 7 27 20 PM](https://github.com/jamesdales/IconMapSupport/assets/92735518/0aa3e242-1d23-43d8-9dea-d2003c9ab3a7)
![Screenshot 2024-01-10 at 7 30 01 PM](https://github.com/jamesdales/IconMapSupport/assets/92735518/7331f127-fad4-4399-90ce-a1b3e8caf1cf)

**Comment by aliciaoberholzer** [comment]
I didn't realize the raw URL always has the same general structure - my apologies, please disregard the comment above and thank you for your help!
