### ISSUE TITLE
Dynamic GeoJSON calls

### ISSUE THREAD

**Issue by bubizar** [jamesdales/IconMapSupport#5]
First, what a fantastic work !

Rather than being fixed, would it be possible to make the geojson URL field dynamic ? (with a measure)
![2023-06-29_17h22_02](https://github.com/jamesdales/IconMapSupport/assets/106630003/dae4b426-8fab-4e67-adae-d02f9f7c3a05)

The idea is to call web services that return a subset of the GeoJSON, particularly during drilling operations. (Only get a part of the city equipments on the neighbourhood concerned for example.)

Thank you very much.
👏

**Comment by jamesdales** [comment]
Hi @bubizar 

Good news is that this has already been added and should be included in the next release in the next few days.

Thanks 

James

**Comment by bubizar** [comment]
You're magic @jamesdales! 🎊
![2023-06-30_16h41_17](https://github.com/jamesdales/IconMapSupport/assets/106630003/651cc4b4-6be8-4f75-8c83-31cee6f56a8d)

Next time I'll check your changelog to avoid this useless thread.

**Comment by jamesdales** [comment]
Ah yes - already added this back in March. I'll close the issue.
