### ISSUE TITLE
[Icon Map Pro] Missing Features from Icon Map PRO

### ISSUE THREAD

**Issue by AlyafeiAli** [jamesdales/IconMapSupport#60]
Hi,

One of the best features of Icon Map is the ability to dynamically change the background using measures. (I used different mapbox backgrounds)    
I'm trying Icon Map Pro but I can't seem to find this option any longer.. I hope it gets implemented soon 😊

This the feature that's missing:  
![image](https://github.com/jamesdales/IconMapSupport/assets/52626961/32c765dc-ae0a-4d65-aac2-5bbe2cb9d5bb)

UPDATE: I just noticed that WMS Layer's name is also no longer dynamic.  

This is how it used to be:  
![image](https://github.com/jamesdales/IconMapSupport/assets/52626961/64d7014a-c8c4-45a7-8c53-2e649a88c58c)

**Comment by jamesdales** [comment]
Hi @AlyafeiAli 

The good news is, you can still set a bespoke background map using Icon Map Pro, in the same way as was possible in Icon Map.

The option is in the Raster (or Vector *new in Icon Map Pro*) tiles configuration. 

![image](https://github.com/jamesdales/IconMapSupport/assets/37669155/790f73e8-5d94-47d9-963c-1f25a3a06ab1)

These both still work with Mapbox background, and you can now also use the vector tiles, which can look nicer.

WMS layers set with conditional formatting didn't make the first release, but it's on the backlog (with lots of other improvements) and should arrive soon.

Thanks

James

**Comment by AlyafeiAli** [comment]
Hi @jamesdales  
First of all let me congratulate you on launching your new company and IconMapPro. I'm really happy for you!

Thank you for pointing me towards the Raster option, it's working perfectly!  

P.S., I was wondering if it's possible to implement #58 in Icon Map Pro, that would be great :)

**Comment by AlyafeiAli** [comment]
solved in version 1.0.0.2, thank you 👍🏼
