### ISSUE TITLE
[IconMapPro] Feature request: Dynamically change Vector Tiles Layer URL and Clusters 

### ISSUE THREAD

**Issue by AlyafeiAli** [jamesdales/IconMapSupport#65]
Hi again,

Is it possible to allow us to dynamically change the Vector Tiles Layer URL?   
It would also be awesome if we could do that the Clusters as well ( under Circles ).

Thanks!

**Comment by jamesdales** [comment]
Hi @AlyafeiAli 

Would you mind sending these to support@iconmappro.com as we're maintaining a separate request list for Icon Map Pro from the old Icon Map, and there's a high likelyhood I won't see them here.

**Comment by AlyafeiAli** [comment]
Sure thing, I’ll send an email right away.  
thank you :)
